# Generated by Django 4.2.1 on 2023-06-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Marchant'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
