# Generated by Django 4.2.1 on 2023-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_user_options_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('merchant', 'Merchant')], default='merchant', max_length=50, null=True),
        ),
    ]
