# Generated by Django 4.2.1 on 2023-06-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('merchant', 'Merchant')], default='merchant', max_length=50),
        ),
    ]
