# Generated by Django 4.2.1 on 2023-06-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_alter_profilepicture_img_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
