# Generated by Django 4.2.1 on 2023-06-08 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepicture',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
