# Generated by Django 4.2.1 on 2023-06-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_profilepicture_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='img',
            new_name='image',
        ),
    ]
