# Generated by Django 4.2.1 on 2023-06-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcategory__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='_id',
        ),
    ]
