# Generated by Django 4.2.1 on 2023-06-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shopName',
            new_name='title',
        ),
    ]
