# Generated by Django 4.2.1 on 2023-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='connection',
            field=models.ManyToManyField(to='shop.shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='request_sender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
