# Generated by Django 4.2.1 on 2023-06-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_shop_request_sender_shop_request_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='request_sender',
        ),
        migrations.AddField(
            model_name='shop',
            name='request_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_senders', to='shop.shop'),
        ),
    ]
