# Generated by Django 4.2.1 on 2023-06-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_shop_request_sender_shop_request_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='merchant',
        ),
    ]
