# Generated by Django 4.2.1 on 2023-06-02 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
