# Generated by Django 4.2.1 on 2023-06-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_connection__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='request_sender',
        ),
    ]
