# Generated by Django 4.2.1 on 2023-06-05 05:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_shop_request_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
