# Generated by Django 4.2.1 on 2023-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_shop_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='merchant', max_length=50, null=True),
        ),
    ]
