# Generated by Django 4.2.1 on 2023-06-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_connection_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcategory',
            old_name='_id',
            new_name='uuid',
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
