# Generated by Django 4.2.1 on 2023-06-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_rename__id_shopcategory_uuid_alter_shopcategory_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcategory',
            old_name='uuid',
            new_name='_id',
        ),
    ]
