# Generated by Django 4.2.1 on 2023-06-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_rename_uuid_shopcategory__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcategory',
            old_name='_id',
            new_name='uuid',
        ),
    ]
