# Generated by Django 4.2.1 on 2023-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rename__id_shopcategory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
