# Generated by Django 4.2.1 on 2023-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_shopcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='connection',
            field=models.ManyToManyField(blank=True, to='shop.shop'),
        ),
    ]
