# Generated by Django 4.2.1 on 2023-06-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_shop_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='_id',
            new_name='uuid',
        ),
    ]
