# Generated by Django 4.2.1 on 2023-06-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_rename__id_shop_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='_id',
            new_name='uuid',
        ),
    ]
