# Generated by Django 4.2.1 on 2023-06-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_shop_category_alter_shop_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
