# Generated by Django 4.2.1 on 2023-06-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], max_length=50, null=True),
        ),
    ]
