# Generated by Django 4.2.1 on 2023-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cart_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
