# Generated by Django 4.2.1 on 2023-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shoppingcart_shop_alter_shoppingcart_quantity'),
        ('orders', '0005_alter_orderproduct_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cart_items',
            field=models.ManyToManyField(to='cart.shoppingcart'),
        ),
    ]
