# Generated by Django 4.2.1 on 2023-06-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderproduct_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cart_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
