# Generated by Django 4.2.1 on 2023-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderproduct_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
