# Generated by Django 4.2.1 on 2023-06-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderproduct_total_price_orderproduct_total_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='_id',
            new_name='uuid',
        ),
    ]
