# Generated by Django 4.2.1 on 2023-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename__id_orderproduct_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cart_items',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='is_pay',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total_qty',
            field=models.IntegerField(blank=True),
        ),
    ]
