# Generated by Django 4.2.1 on 2023-06-07 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0029_alter_connection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='shop.shop')),
            ],
        ),
    ]
